[changelog]
header = """
# Changelog

"""

body = """
## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d %H:%M") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits %}
{%- if commit.scope -%}
- *({{ commit.scope }})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{ link.text }}]({{ link.href }}) {% endfor -%}){% endif %} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/ws-io/wsio-rs/commit/{{ commit.id | truncate(length=7, end="") }}))
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{ link.text }}]({{ link.href }}) {% endfor -%}){% endif %} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/ws-io/wsio-rs/commit/{{ commit.id | truncate(length=7, end="") }}))
{% endif -%}
{% endfor -%}
{% endfor %}
"""

commit_parsers = [
  { message = "^feat", group = "ğŸš€ Enhancements" },
  { message = "^fix", group = "ğŸ©¹ Fixes" },
  { message = "^perf", group = "ğŸ”¥ Performance" },
  { message = "^refactor", group = "ğŸ’… Refactors" },
  { message = "^docs", group = "ğŸ“– Documentation" },
  { message = "^style", group = "ğŸ¨ Styles" },
  { message = "^examples", group = "ğŸ€ Examples" },
  { message = "^types", group = "ğŸŒŠ Types" },
  { message = "^test", group = "âœ… Tests" },
  { message = "^build", group = "ğŸ“¦ Build" },
  { message = "^ci", group = "ğŸ¤– CI" },
  { message = "^chore", group = "ğŸ¡ Chore" },
  { message = "^.*", group = "ğŸ“Œ Others" },
]
